# yamllint disable rule:line-length
---
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - content/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to S3
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: Live
      url: https://osborn.io

    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Sync content to the S3 bucket
        run: |
          aws s3 sync content/ "s3://${BUCKET_NAME}" --sse AES256 --no-progress --delete
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Invalidate the CloudFront distribution
        run: |
          readonly batch="${RUNNER_TEMP:?}/invalidation-batch.json"
          trap 'rm -f "${batch}"' EXIT
          jq -n --arg s "${GITHUB_SHA:?}" '{Paths:{Quantity:1,Items:["/*"]},CallerReference:("sha-"+$s)}' >"${batch}"
          aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --invalidation-batch "file://${batch}"
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
